### ISSUE TITLE
Smart messages: Go-to step (scrolling) only goes up to 16

### ISSUE THREAD

**Issue by imranino** [Pirate-MIDI/Pirate-MIDI-BridgeOS#159]
**Device:**
 - Device: Bridge6
 - Firmware version: v1.2.2
 - Hardware version:  v1.0

**Describe the bug**
Trying to set a bank message to send a particular scrolling step when it loads. But the steps are limited to 16

**To Reproduce**
1. in the editor
2. Bank settings
3. bank messages
4. custom
5. smart messages
6. go to step (scrolling)
7. only 1-16 available

**Expected behavior**
on step 7. above, steps 1-127 should be available
**Screenshots**
![Screenshot 2023-03-06 at 15 52 24](https://user-images.githubusercontent.com/66065294/223146575-0d917d86-e872-4663-9e52-175c3827cebd.jpg)

**Comment by imranino** [comment]
ditto if trying to set it this up directly onboard

**Comment by simonaglover95** [comment]
@imranino seems like you need to watch the video tutorial I'm about to release haha! Those smart messages aren't about skipping the scroll to a particular CC value, but about selecting a particular message in the scrolling stack (limit of 16 messages in the stack) rather than have all messages in the stack be inc/decremented at once :)
