### ISSUE TITLE
Wrong execution order of messages in toggle mode

### ISSUE THREAD

**Issue by mrcury** [Pirate-MIDI/Pirate-MIDI-BridgeOS#174]
**Device(please complete the following information):**
 - Device: Bridge6
 - Firmware version: 1.2.2
 - Hardware version: 1.1.3

**Describe the bug**
When adding a series of midi CC messages to the toggle mode in switch 1, the order of messages is not sent out as entered in the editor. I had added a series of instructions to the switch group and these were the cause of the misfiring.

So the problem is actually that when the switch group rules are removed from the editor these changes are not sent to the device. If I import back from the device the rules are still there.

**To Reproduce**
1. Add switch group rules to Bank 1
2. Send to device
3. Remove switch group rules from Bank 1
4. Import settings from device
5. Switch group rules are back

**Expected behavior**
When removing switch group rules from banks and sent they should be removed from the device as well.

**Comment by mrcury** [comment]
Sorry, I submit the bug before finishing! Here is my current config file:
[Bridge 6_2023-03-23_11-43-51.json.zip](https://github.com/Pirate-MIDI/Pirate-MIDI-BridgeOS/files/11049818/Bridge.6_2023-03-23_11-43-51.json.zip)

**Comment by mrcury** [comment]
Also, probably a separate bug:

the message order is sent incorrectly from the editor to the device. When inspecting the message order on the device itself they are entered as 

ch 12 - cc 26 - msg 0
ch 12 - cc 22 - msg 0

while they should have been

ch 12 - cc 22 - msg 0
ch 12 - cc 26 - msg 0

**Comment by samspencer5991** [comment]
I'm really not sure I follow with what the issue is here.
Unless I'm mistaken, you're saying that you are assigning something in the editor (in your case, switch groups), sending that config to the device. Then in the editor, removing that assignment, then importing the device config back in from the device?
Of course it will still have that assignment, because you are importing it from the device. That is exactly how it should work.

Regarding your second comment, that needs to be a separate issue, please do not combine things in that way.
